acapy.unavailable=aca-py not available

api.chat.error.incoming=Error saving (incoming) chat message
api.chat.error.outgoing=Error saving (outgoing) chat message

api.diddoc.malformed.url=Malformed endpoint URL: {url}
api.diddoc.partner.call.failed=Call to partner web endpoint failed - msg: {msg}
api.diddoc.resolution.error=Could not resolve did document (wrong did?)

api.document.not.found=No document found for id: '{id}'
api.document.validation.empty=Document does not exist in database
api.document.validation.type.changed=Document type can not be changed after creation
api.document.validation.schema.id.missing=A document of type indy_credential must have a schema id set.
api.document.validation.attribute.not.in.schema=Attribute: '{attr}' is not a part of the schema
api.document.validation.profile.already.exists=Organizational profile already exists, use update instead

api.credential.no.match=aca-py has no matching credential exchange record
api.holder.credential.exchange.declined=Holder declined credential offer: no reason provided
api.holder.issuer.has.no.creddef=Issuer has no operable credential  definition for proposal spec: '{id}'

api.invitation.empty=Invitation was empty
api.invitation.url.invalid=Invitation Url does not contain a known or valid invitation.
api.invitation.parsing.error=Error parsing invitation {message}
api.invitation.decoding.error=Invitation Url could not be decoded. Cannot determine invitation details.
api.invitation.decoding.error.not.v1=Expecting a valid Connections 1.0 invitation; could not parse data.
api.invitation.decoding.error.not.oob=Expecting a valid Out Of Band 1.0 invitation; could not parse data.
api.invitation.decoding.error.unsupported.type=Unknown or unsupported Invitation type. @type = {type}
api.invitation.decoding.error.empty.result=Invitation could not be decoded; result was empty

api.issuer.credential.document.mismatch=Document attributes {doc} do not match schema attributes {schema}
api.issuer.credential.exchange.problem=Credential could not be issued, because the proposal is not active any more
api.issuer.credential.exchange.declined=Issuer declined credential proposal: no reason provided
api.issuer.credential.missing.revocation.info=Credential can not be revoked (missing revocation flag)
api.issuer.credential.send.offer.wrong.state=Wrong exchange state expected: proposal received but was: {state}
api.issuer.credential.send.offer.wrong.creddef=Provided credential definition id is not configured
api.schema.credential.document.conversion.failure=Only documents that are based on a schema can be converted into a credential
api.issuer.creddef.already.exists=Credential definition for schema '{id}' already exists with tag '{tag}'
api.issuer.creddef.ledger.failure=Credential Definition not created; could not complete request with ledger
api.issuer.creddef.in.use=Credential Definition cannot be deleted, it has been used to issue credentials
api.issuer.creddef.not.found=Could not find credential definition with id '{id}'
api.issuer.no.tails.server=Credential revocation is not supported (tails server not configured)
api.issuer.schema.failure=Could not add schema with id '{id}' to database.
api.issuer.reissue.wrong.state=Can not reissue credential, wrong state expected 'revoked' but found found '{state}'

api.org.profile.name=Organizational Profile

api.partner.not.found=No partner found for id: '{id}'
api.partner.no.connection=Partner has no aca-py connection
api.partner.already.exists=Partner for did already exists: '{id}'
api.partner.lookup.no.did.doc=Could not retrieve did document from ledger
api.partner.lookup.no.endpoint=Could not retrieve public profile from endpoint: {endpoint}
api.partner.proof.request.empty.body=One of requestBySchema or requestRaw must be set.
api.partner.proof.request.no.schema.id=Schema id must not be empty

api.proof.exchange.declined=User Declined Proof Request: No reason provided
api.proof.exchange.wrong.state=PresentationExchangeState != 'request-received'
api.proof.exchange.no.match=No matching credentials found for proof request: '{id}'
api.proof.exchange.abandoned=Partner rejected proof exchange because it is not valid
api.proof.exchange.default.name=Proof Request
api.present.proof.wrong.state=PresentationExchangeRole!= 'prover' or PresentationExchangeState != 'request-received'

api.proof.template.constraint.violation=Template can not be deleted because it is still in use.
api.proof.template.not.found=No proof template found for: '{id}'

api.schema.not.found=Schema with id: '{id}' does not exist
api.schema.creation.failed=Schema not created; could not complete request with ledger
api.schema.creation.adding.failed=Schema config could not be added
api.schema.creation.general.error=Schema not created. {message}
api.schema.ledger.error=Error sending schema to ledger. {message}
api.schema.already.exists=Schema with id: '{id}' already exists
api.schema.already.exists.ledger=Schema with id: '{id}' does not exist on the ledger.
api.schema.constrain.violation=Schema can not be deleted, because it is still used by a trusted issuer or credential definition
api.schema.restriction.already.configured=Trusted issuer: '{did}' already configured for this schema
api.schema.restriction.issuer.not.found=Did '{did}' does not exist on the ledger
api.schema.restriction.schema.not.found=Schema with id: '{id}' is not configured
api.schema.restriction.schema.not.found.on.ledger=No schema with id '{id}' found on ledger
api.schema.ld.id.parse.error=Expecting a valid URI as schema id

api.tag.already.exists=Tag with name: {name} already exists.
api.tag.constraint.violation=Tag is still used by '{count}' partner(s)